# ?????? ??????????
appenders = myappender

# ????????? RollingFile
appender.myappender.type = RollingFile
appender.myappender.name = FILE
appender.myappender.fileName = logs/hippodrome.log
# 1. filePattern ?????? ???? ????????? ?????? ?????????, ? ?? ??????!
appender.myappender.filePattern = app-%d{yyyy-MM-dd}-%i.log

# 2. ????????? ?????? ?????? (Layout) ? ????? ?????? ???? PatternLayout
appender.myappender.layout.type = PatternLayout
appender.myappender.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

# 3. ??? RollingFile ??????????? ????? ??????? ??????? (Policies)
appender.myappender.policies.type = Policies
appender.myappender.policies.time.type = TimeBasedTriggeringPolicy
appender.myappender.policies.time.interval = 1

# ????????? ????????? ??????? (????????? ??????? ??????)
rootLogger.level = debug
rootLogger.appenderRefs = myfile
rootLogger.appenderRef.myfile.ref = FILE

